### ISSUE TITLE
Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past.

### ISSUE THREAD

**Issue by synoga** [ValveSoftware/GameNetworkingSockets#112]
Hi,
I've been playing with these sockets for some time now, making a client and a server with it.
It's globally a real pleasure to use, but I've stumbled upon some problem.

Once in a while, when the server stays idle for a few hours, the socket is closed with this error message :
` ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp(2725): Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past`

It's very random (sometimes 2 hours, sometimes 6), so hard to reproduce. Reading the source I could learn that _If some code is setting a think time for right now, then it should have just done it_, which makes sense. But right now I'm just learning how to use these sockets, I only use basic features and I don't handle any of those parts myself, so I don't really know where to go from here.

I'm using v1.1.0 built with clang 10 on arch linux if that's of any use.

**Comment by fletcherdvalve** [comment]
Do you have a stack trace?  Can you run under the debugger?

**Comment by synoga** [comment]
I can run under the debugger. I'll post the stack trace next time the problem occurs.

**Comment by synoga** [comment]
Here is more information :

```# error message
7795.288674 ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp(2725): Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past

# stack trace
1  abort                                                                                                                                       0x7f6473a1272c 
2  __gnu_cxx::__verbose_terminate_handler                                                          vterminate.cc                          95   0x7f6473dab81d 
3  __cxxabiv1::__terminate                                                                         eh_terminate.cc                        48   0x7f6473db82ca 
4  std::terminate                                                                                  eh_terminate.cc                        58   0x7f6473db8337 
5  __cxxabiv1::__cxa_throw                                                                         eh_throw.cc                            95   0x7f6473db859e 
6  ServerNetworkManager::debugOutput                                                               servernetworkmanager.cpp               263  0x556c10be3bb7 
7  SteamNetworkingSocketsLib::SDRSpewFunc                                                          steamnetworkingsockets_lowlevel.cpp    1777 0x7f6473fe0c1e 
8  _SpewMessageType                                                                                dbg.cpp                                211  0x7f64740010d9 
9  _SpewMessage                                                                                    dbg.cpp                                236  0x7f647400101f 
10 AssertMsgImplementation                                                                         dbg.cpp                                289  0x7f6474001261 
11 SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::CheckConnectionStateAndSetNextThinkTime steamnetworkingsockets_connections.cpp 2725 0x7f6473fd9686 
12 SteamNetworkingSocketsLib::ProcessThinkers                                                      steamnetworkingsockets_lowlevel.cpp    1302 0x7f6473fdfb78 
13 SteamNetworkingSocketsLib::SteamNetworkingSockets_InternalPoll                                  steamnetworkingsockets_lowlevel.cpp    1386 0x7f6473fe15ad 
14 SteamNetworkingSocketsLib::SteamNetworkingThreadProc                                            steamnetworkingsockets_lowlevel.cpp    1477 0x7f6473fe0d2c 
15 std::__invoke_impl<void, void ( *)()>                                                           invoke.h                               60   0x556c109525a7 
16 std::__invoke<void ( *)()>                                                                      invoke.h                               95   0x556c1095253d 
17 std::thread::_Invoker<std::tuple<void ( *)()>>::_M_invoke<0ul>                                  thread                                 244  0x556c10952515 
18 std::thread::_Invoker<std::tuple<void ( *)()>>::operator()                                      thread                                 251  0x556c109524e5 
19 std::thread::_State_impl<std::thread::_Invoker<std::tuple<void ( *)()>>>::_M_run                thread                                 195  0x556c109523ce 
20 std::execute_native_thread_routine                                                              thread.cc                              80   0x7f6473de4b24 
21 start_thread                                                                                                                                0x7f6473f0c46f 
22 clone                                                                                                                                       0x7f6473aec3d3 

# backtrace for the relevant threads (error happened on thread 7)
Thread 8 (Thread 0x7f645f570700 (LWP 103837)):
#0  0x00007f6473f164cf in __lll_lock_wait () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00007f6473f0ee91 in pthread_mutex_lock () from /usr/lib/libpthread.so.0
No symbol table info available.
#2  0x00007f6473fde003 in __gthread_mutex_lock (__mutex=0x7f6474041600 <SteamNetworkingSocketsLib::s_steamDatagramTransportMutex>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:749
No locals.
#3  __gthread_recursive_mutex_lock (__mutex=0x7f6474041600 <SteamNetworkingSocketsLib::s_steamDatagramTransportMutex>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:811
No locals.
#4  std::recursive_timed_mutex::lock (this=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/mutex:251
        __e = <optimized out>
#5  SteamNetworkingSocketsLib::SteamDatagramTransportLock::Lock (pszTag=0x7f6474020317 "ReceiveMessagesOnPollGroup") at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp:131
        usecTimeStartedLocking = 3007796763739
#6  0x00007f6473fcee64 in SteamNetworkingSocketsLib::SteamDatagramTransportLock::SteamDatagramTransportLock (this=<optimized out>, pszTag=0x7f6474041600 <SteamNetworkingSocketsLib::s_steamDatagramTransportMutex> "\002") at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.h:337
No locals.
#7  SteamNetworkingSocketsLib::CSteamNetworkingSockets::ReceiveMessagesOnPollGroup (this=<optimized out>, hPollGroup=2147549184, ppOutMessages=0x7f645f56fda0, nMaxMessages=1) at ../src/steamnetworkingsockets/clientlib/csteamnetworkingsockets.cpp:813
        pPollGroup = <optimized out>
        scopeLock = <optimized out>
#8  0x0000556c10be3d91 in ServerNetworkManager::PollIncomingMessages (this=0x556c115e4138 <ServerNetworkManager::getInstance()::instance>) at ../../src/server/udp/servernetworkmanager.cpp:189
        pIncomingMsg = 0x0
        numMsgs = 0
#9  0x0000556c10be3cd2 in ServerNetworkManager::steamSocketNetworkLoop (this=0x556c115e4138 <ServerNetworkManager::getInstance()::instance>) at ../../src/server/udp/servernetworkmanager.cpp:213
No locals.
#10 0x0000556c10be6147 in std::__invoke_impl<void, void (ServerNetworkManager::*)(), ServerNetworkManager*> (__f=@0x556c1f4c48f0: (void (ServerNetworkManager::*)(ServerNetworkManager * const)) 0x556c10be3c90 <ServerNetworkManager::steamSocketNetworkLoop()>, __t=@0x556c1f4c48e8: 0x556c115e4138 <ServerNetworkManager::getInstance()::instance>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/invoke.h:73
No locals.
#11 0x0000556c10be6052 in std::__invoke<void (ServerNetworkManager::*)(), ServerNetworkManager*> (__fn=@0x556c1f4c48f0: (void (ServerNetworkManager::*)(ServerNetworkManager * const)) 0x556c10be3c90 <ServerNetworkManager::steamSocketNetworkLoop()>, __args=@0x556c1f4c48e8: 0x556c115e4138 <ServerNetworkManager::getInstance()::instance>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/invoke.h:95
No locals.
#12 0x0000556c10be6015 in std::thread::_Invoker<std::tuple<void (ServerNetworkManager::*)(), ServerNetworkManager*> >::_M_invoke<0ul, 1ul> (this=0x556c1f4c48e8) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:244
No locals.
#13 0x0000556c10be5fc5 in std::thread::_Invoker<std::tuple<void (ServerNetworkManager::*)(), ServerNetworkManager*> >::operator() (this=0x556c1f4c48e8) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:251
No locals.
#14 0x0000556c10be5d8e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (ServerNetworkManager::*)(), ServerNetworkManager*> > >::_M_run (this=0x556c1f4c48e0) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:195
No locals.
#15 0x00007f6473de4b24 in std::execute_native_thread_routine (__p=0x556c1f4c48e0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x556c1f4c48e0}
#16 0x00007f6473f0c46f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#17 0x00007f6473aec3d3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 7 (Thread 0x7f645fd71700 (LWP 103836)):
#0  0x00007f6473a1272c in abort () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f6473dab81d in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#2  0x00007f6473db82ca in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
No locals.
#3  0x00007f6473db8337 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
No locals.
#4  0x00007f6473db859e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7f6473ef0380 <typeinfo for std::runtime_error>, dest=0x7f6473dce7f0 <std::runtime_error::~runtime_error()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
        globals = <optimized out>
        header = 0x7f6430013890
#5  0x0000556c10be3bb7 in ServerNetworkManager::debugOutput (eType=k_ESteamNetworkingSocketsDebugOutputType_Bug, pszMsg=0x7f645fd70420 "../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp(2725): Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past") at ../../src/server/udp/servernetworkmanager.cpp:263
        time = 7795288674
#6  0x00007f6473fe0c1e in SteamNetworkingSocketsLib::SDRSpewFunc (type=SPEW_ASSERT, pMsg=0x7f645fd70420 "../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp(2725): Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past") at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp:1777
No locals.
#7  0x00007f64740010d9 in _SpewMessageType (spewType=SPEW_ASSERT, pMsgFormat=0x7f6474022efb "%s", args=0x7f645fd70900) at ../src/tier0/dbg.cpp:211
        pTempBuffer = "../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp(2725): Assertion Failed: Scheduled next think time must be in in the future.  It's 0usec in the past\000\000\000\000\000|/\000\060d\177\000\000\270/\000\060d\177\000\000\240\017\000\000\000\000\000\000\030?\000\060d\177\000\000l/\000\060d\177\000\000\377\377\377\377\000\000\000\000\220\016\000\060d\177\000\000x/\000\060d\177\000\000\030?\000\060d\177\000\000\377\377\377\377\000\000\000\000q\370\377sd\177\000\000\220\372\003td\177\000\000\020\020\000\060\315\314L=l/\000\060d\177\000\000\250\005\327_d\177\000\000\070", '\000' <repeats 15 times>, "\377\377\377\377\000\000\000\000Ú\333sd\177\000\000\020\020\000\060d\177\000\000p\211\001td\177\000\000\020\020\000\060d\177\000\000\355\270\377sd\177\000\000\237\002\233A\005\334%EOk\361sd\177\000\000\001\000\000\000\000\000\000\000\330\006\327_d\177\000\000\001\000\000\000\000\000\000\000\000\277\207:", '\000' <repeats 12 times>, "?\370\375sd\177\000\000\200\064\000Xd\177\000\000\220\016\000\060d\177\000\000\260\025\001\060d\177\000\000b\b\002td\177\000\000I-\002td\177\000\000\375}\376sd\177\000\000\000\205\000\020\b/\000\000\000\000\000\006j\004\200\000\350?\000\060d\177\000\000\021S\003\000\000\000\000\000\020E\000\060d\177\000\000\350D\000\060d\177\000\000PA\000\060d\177\000\000\236M\002td\177\000\000\030E\000\060d\177\000\000\340D\000\060d\177\000\000\220[\000\060d\177\000\000\220\016\000\060d\177\000\000\003A\250N\274\002\000\000`\352\000\000\000\000\000\000\260D\000\060d\177\000\000\340\006\327_d\177\000\000N\v\327_d\177\000\000\000\277\207:\263X@aP\n\327_d\177\000\000\000\000\000\000\000\000\000\000\376\000\000\000\000\000\000\000\340\006\327_d\177\000\000c\361\001td\177\000\000\020\t\327_d\177\000\000P\n\327_d\177\000\000Ê´\246sd\177\000\000\020\020\000\060d\177\000\000\320\a\327_d\177\000\000\001\200\255\373\000\000\000\000P\n\327_d\177\000\000P\n\327_d\177\000\000P\n\327_d\177\000\000P\n\327_d\177\000\000\255\n\327_d\177\000\000N\v\327_d\177\000\000P\n\327_d\177\000\000N\v\327_d\177", '\000' <repeats 42 times>, "\001\016\000\060\200\000\000\000\001\016\000\060\000\000\000\000\000\000\327_d\177\000\000\000\000\000\000\000\000\000\000\272\071\002\304\000\000\000\000\260[\250N\274\002\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 12 times>, "d\177\000\000\300\f\004td\177\000\000\377\377\377\377", '\000' <repeats 21 times>, "\340\272sd\177", '\000' <repeats 19 times>, "\277\207:\263X@a\220\016\000\060d\177\000\000\377\377\377\377\377\377\377\177\260[\250N\274\002\000\000\020\000\000\000\000\000\000\000\020\262\376sd\177\000\000\260[\250N\274\002\000\000\003\016\377sd\177\000\000\270\001>sd\177\000\000\000\277\207:\263X@a"
        len = <optimized out>
        val = <optimized out>
        ret = <optimized out>
#8  0x00007f647400101f in _SpewMessage (pMsgFormat=0x7f6473bad4a3 <_IO_2_1_stderr_+131> "\n") at ../src/tier0/dbg.cpp:236
        args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7f645fd70930, reg_save_area = 0x7f645fd70850}}
        ret = <optimized out>
#9  0x00007f6474001261 in AssertMsgImplementation (_msg=0x7f6473bad4a3 <_IO_2_1_stderr_+131> "\n", _bFatal=<optimized out>, pstrFile=0x1 <error: Cannot access memory at address 0x1>, nLine=1940772255, bFullDump=10) at ../src/tier0/dbg.cpp:289
        s_ThreadLocalAssertMsgGuardStatic = 1
        s_bDisableDebuggerBreak = false
        ret = <optimized out>
#10 0x00007f6473fd9686 in SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::CheckConnectionStateAndSetNextThinkTime (this=0x7f6430000e90, usecNow=3007796763568) at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp:2725
        usecMinNextThinkTime = 3007796763568
#11 0x00007f6473fdfb78 in SteamNetworkingSocketsLib::ProcessThinkers () at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp:1302
        pNextThinker = 0x7f6430000e90
        usecNow = 3007796763568
        nIterations = 1
#12 0x00007f6473fe15ad in SteamNetworkingSocketsLib::SteamNetworkingSockets_InternalPoll (msWait=<optimized out>, bManualPoll=false) at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp:1386
No locals.
#13 0x00007f6473fe0d2c in SteamNetworkingSocketsLib::SteamNetworkingThreadProc () at ../src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp:1477
        sched = {sched_priority = 0}
        policy = <optimized out>
        thread = <optimized out>
#14 0x0000556c109525a7 in std::__invoke_impl<void, void (*)()> (__f=@0x556c11f9e858: 0x7f6473fe0c30 <SteamNetworkingSocketsLib::SteamNetworkingThreadProc()>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/invoke.h:60
No locals.
#15 0x0000556c1095253d in std::__invoke<void (*)()> (__fn=@0x556c11f9e858: 0x7f6473fe0c30 <SteamNetworkingSocketsLib::SteamNetworkingThreadProc()>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/invoke.h:95
No locals.
#16 0x0000556c10952515 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul> (this=0x556c11f9e858) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:244
No locals.
#17 0x0000556c109524e5 in std::thread::_Invoker<std::tuple<void (*)()> >::operator() (this=0x556c11f9e858) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:251
No locals.
#18 0x0000556c109523ce in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run (this=0x556c11f9e850) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../include/c++/9.3.0/thread:195
No locals.
#19 0x00007f6473de4b24 in std::execute_native_thread_routine (__p=0x556c11f9e850) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
        __t = std::unique_ptr<std::thread::_State> = {get() = 0x556c11f9e850}
#20 0x00007f6473f0c46f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#21 0x00007f6473aec3d3 in clone () from /usr/lib/libc.so.6
No symbol table info available.```

**Comment by fletcherdvalve** [comment]
Thanks, @synoga.  I just tweaked the assert, so that it will be more useful for tracking down the bug.  If you have some time, could you run your test again and give me the call stack?

**Comment by synoga** [comment]
Thanks for your commit @fletcherdvalve , I'm in the middle of a large refactoring and I'm not able to build my project at the moment, I'll get back to you asap!

**Comment by synoga** [comment]
@fletcherdvalve : I have an instance of my server running for several days now and I am unable to reproduce the previous situation. Maybe we can close this issue and reopen later it if need be?

**Comment by fletcherdvalve** [comment]
It's possible I tweaked the logic slightly and fixed the bug.  Thanks for checking.  If you see it again, please share the call stack.
